#volumes:
#            - mariadb-volumes:    /home/login/data/MariaDB

version: '3.8'

services:
  ###############################
  #           nginx             #
  ###############################
    nginx:
        hostname: nginx
        container_name: nginx
        image: nginx
        restart: always
        ports:
             - "443:443"
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        networks:
            -Inception:
        env_file: .env

  ###############################
  #           MariaDB           #
  ###############################
    mariadb:
        hostname: MariaDB
        container_name: MariaDB
        image: mariadb
        restart: always
        build:
            context: ./requirements/MariaDB
            dockerfile: Dockerfile
        networks:
            -Inception:
        environment:
          - WP_DB=${WP_DB}
          - WP_DB_USER=${WP_DB_USER}
          - WP_DB_PWD=${WP_DB_PWD}
          - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}

        env_file: .env
        volumes:
            - '/home/rcuminal/data/DBvol:/var/lib/mysql'


networks:
      -Inception: