#volumes:
#            - mariadb-volumes:    /home/login/data/MariaDB

version: '3.8'

services:
  ###############################
  #           nginx             #
  ###############################
    nginx:
        hostname: nginx
        container_name: nginx
        image: nginx
        restart: always
        ports:
             - "443:443"
        build:
            context: ./requirements/nginx
            context: ./requirements/nginx
            dockerfile: Dockerfile
      #  networks:
      #      inception:
        env_file: .env