#volumes:
#            - mariadb-volumes:    /home/login/data/MariaDB

version: '3.8'

services:

  ###############################
  #           MariaDB           #
  ###############################
    mariadb:
        hostname: mariadb
        container_name: mariadb
        image: mariadb
        restart: always
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        networks:
            -Inception:
        env_file: .env
        volumes:
            - '/home/rcuminal/data/DBvol:/var/lib/mysql'

  ###############################
  #           WordPress         #
  ###############################
    wordpress:
        depends_on:
                - mariadb
        hostname: wordpress
        container_name: wordpress
        image: wordpress
        restart: always
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        networks:
            -Inception:
        env_file: .env
        volumes:
            - '/home/rcuminal/data/WPvol:/var/www/wordpress'

  ###############################
  #           nginx             #
  ###############################
    nginx:
        depends_on:
            - wordpress
            - mariadb
        hostname: nginx
        container_name: nginx
        image: nginx
        restart: always
        ports:
             - "443:443"
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        networks:
            -Inception:
        env_file: .env
        volumes:
            - '/home/rcuminal/data/WPvol:/var/www/wordpress'
            
networks:
      -Inception: